version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: >
      /bin/bash -c "
      python /code/social_network/manage.py migrate &&
      python /code/social_network/manage.py runserver 0.0.0.0:8000
      "
